### ISSUE TITLE
Not auto subscribing to dispatch qb-core

### ISSUE THREAD

**Issue by norwayRP** [Wick89/FirescriptAddons#1]
Hi
Not getting the auto subscribe function for qb-core to work. It works if I do /firedispatch add (id)

Only thing changed is job name since mine is lsfd not ambulance.

**Comment by Wick89** [comment]
My bad have it to Config.Dispatch.Framework == "sl" where we use sl-core

Have now fix it to Config.Dispatch.Framework == "qb"
