### ISSUE TITLE
Getting notify error.

### ISSUE THREAD

**Issue by norwayRP** [Wick89/FirescriptAddons#2]
![image](https://user-images.githubusercontent.com/45201861/147496936-7ac7161d-4090-4d39-8642-250d375e347c.png)

**Comment by Wick89** [comment]
Go in firescript go in server.lua go down to AUTO-SUBSCRIBE and look for QBCore.Functions.Notify
And add you owen Notify in.

**Comment by norwayRP** [comment]
I am using this
`QBCore.Functions.Notify("Your subscribe to fire call!", "police")`

So why am I getting nil value then? This is the right function

**Comment by Wick89** [comment]
try TriggerClientEvent('QBCore:Notify', v, 'Your unsubscribe from fire call!', 'police')
or
TriggerClientEvent('QBCore:Notify', src, 'Your unsubscribe from fire call!', 'police')

**Comment by norwayRP** [comment]
> try TriggerClientEvent('QBCore:Notify', v, 'Your unsubscribe from fire call!', 'police') or TriggerClientEvent('QBCore:Notify', src, 'Your unsubscribe from fire call!', 'police')

Have tried both, if I do
`TriggerClientEvent('QBCore:Notify', src, 'Your unsubscribe from fire call!', 'police')`
I do not get any notification at all, but do not get the error.

**Comment by norwayRP** [comment]
Just discovered that now random people get assigned to firedispatch when logging in. Not only people with the job lsfd as I set in config.

**Comment by Wick89** [comment]
yea i see have some function dont work
so i need to add a new function in config
```Config.fireJobs = "add you job here"```
