### ISSUE TITLE
On/off Duty does no re register to dispatch

### ISSUE THREAD

**Issue by norwayRP** [Wick89/FirescriptAddons#3]
Hi, so when you logon and are not on duty there is no way to register back to dispatch, maybe add a function that register to dispatch when going on duty?

**Comment by Wick89** [comment]
Look in wiki have make one to taget

**Comment by Wick89** [comment]
The same, you just have to add it:
```
TriggerServerEvent ("fire: server: firedispatch", source)
```
For your job
Where you have onduty

**Comment by norwayRP** [comment]
Got it, thanks :-)
